language: node_js

node_js:
  - "12"

os:
  - windows
  - linux

deploy:
  provider: npm
  email: ${EMAIL}
  skip_cleanup: true
  api_key:
    secure: ${API_TOKEN}
  on:
    branch: master
    tags: true

before_script: chmod 0777 ./node_modules/.bin/mocha
